server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: my-blog
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "Wzx86699"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000
      pool-name: HikariPool
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.southwestasiafloat.blog: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
